GET http://www.sbb.ch

> {%
  client.global.set("token", "BQDtx2TcSdc7F29vAW0qzKhxG3Ae0siosMukJI1aJvQwZ_lMbzDeezv8MRiG26bkyslQsVI7N1oaZBrlj0iie-vo8UryPMqvb27aTTWBlNjODQEkHZEYvLmsdYInKMQIcNS3NYaHKtQ080u5_ywBfxnR_H27F83PE4OQWBTLLCXxz8JaQLSYYoNkSLyfBUHePXSKSWkFM8TnAoEOm0E8E4lg");
%}

###
GET https://api.spotify.com/v1/me
Authorization: Bearer {{token}}

> {%
    client.global.set("userId", response.body.id);
    client.log("userId=" + client.global.get("userId"))
%}

###
GET https://api.spotify.com/v1/me/playlists
Authorization: Bearer {{token}}

> {%
    client.global.set("playlist", response.body.items[0].id);
    client.log("playlist=" + client.global.get("playlist"))
%}

###
GET https://api.spotify.com/v1/playlists/{{playlist}}
Authorization: Bearer {{token}}

###
GET https://api.spotify.com/v1/me/player/devices
Authorization: Bearer {{token}}

> {%
    client.global.set("playerId", response.body.devices[0].id);
    client.log("playerId=" + client.global.get("playerId"))
%}

###
PUT https://api.spotify.com/v1/me/player
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "device_ids": ["367876aebfb8d523fe095e41a491917ee2b75637"],
  "play": true
}


###
PUT https://api.spotify.com/v1/me/player/play?device_id=9f48ccb7f208758c9dba12617684d5c3ed62668d
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "context_uri": "spotify:playlist:4BgOn9TIlbWK56DTssFrNS",
  "play": true
}
