POST https://api.srgssr.ch/oauth/v1/accesstoken?grant_type=client_credentials
Content-Type: application/x-www-form-urlencoded

client_id = get from account &
client_secret = get from account &
grant_type = client_credentials


> {%
    client.global.clearAll()
    client.global.set("bearertoken", response.body.access_token);
    client.log(response.body.access_token)
%}

###
GET https://api.srgssr.ch/epg/v3/srf/radio/stations/srf-1
Authorization: Bearer {{bearertoken}}
Accept: "application/json"
Accept-Encoding: "identity"

